-- Update music vocabulary table with new content
-- This script will replace all existing music vocabulary with the current CSV data

-- First, clear all existing music vocabulary
DELETE FROM music_vocabulary;

-- Insert new vocabulary data from the current CSV
INSERT INTO music_vocabulary (word, definition) VALUES
('Adagio', 'slowly'),
('Andante', 'at an easy walking pace'),
('Moderato', 'at a moderate speed'),
('Allegro', 'lively and fast'),
('Accelerando (accel.)', 'gradually becoming faster'),
('Allegretto', 'moderately fast'),
('Rallentando (rall.)', 'gradually becoming slower'),
('Ritardando (rit. / ritard.)', 'gradually becoming slower'),
('Ritenuto (riten. / rit.)', 'immediately slower'),
('Largo', 'very slow and stately'),
('Presto', 'very fast'),
('Andantino', 'a little faster than andante'),
('Vivace', 'lively and brisk'),
('Con brio', 'with vigour'),
('Cantabile', 'in a lyrical, singing style'),
('Dolce', 'gently and sweetly'),
('Espressivo', 'with expression'),
('Legato', 'smooth and connected'),
('Staccato', 'short and detached'),
('Marcato', 'stressed and accented'),
('Tenuto', 'held'),
('Forte (f)', 'loud'),
('Piano (p)', 'soft'),
('Mezzo forte (mf)', 'moderately loud'),
('Mezzo piano (mp)', 'moderately soft'),
('Fortissimo (ff)', 'very loud'),
('Pianissimo (pp)', 'very soft'),
('Forte fortissimo (fff)', 'extremely loud'),
('Piano pianissimo (ppp)', 'extremely soft'),
('Sforzando (sf/sfz)', 'a strong, sudden accent'),
('Crescendo (cresc.)', 'gradually becoming louder'),
('Decrescendo (decresc.)', 'gradually becoming softer'),
('Diminuendo (dim.)', 'gradually becoming softer'),
('Ritornello', 'a recurring passage'),
('Da capo (D.C.)', 'from the beginning'),
('Dal segno (D.S.)', 'from the sign'),
('Fine', 'the end'),
('Coda', 'a concluding section'),
('Fermata', 'a pause of unspecified length'),
('Accent', 'emphasis on a note'),
('Slur', 'a curved line connecting notes to be played smoothly'),
('Tie', 'a curved line connecting two notes of the same pitch'),
('Phrase', 'a musical sentence'),
('Motif', 'a short musical idea'),
('Theme', 'a principal melody'),
('Variation', 'a changed version of a theme'),
('Sequence', 'repetition of a pattern at different pitch levels'),
('Imitation', 'repetition of a melody in different voices'),
('Canon', 'a contrapuntal form where voices enter in succession'),
('Fugue', 'a complex contrapuntal form'),
('Counterpoint', 'the combination of two or more melodic lines'),
('Homophony', 'music with a clear melody and accompaniment'),
('Polyphony', 'music with multiple independent melodies'),
('Monophony', 'music with a single melodic line'),
('Texture', 'the way musical lines are combined'),
('Melody', 'a sequence of musical tones'),
('Harmony', 'the combination of simultaneous tones'),
('Rhythm', 'the pattern of durations in music'),
('Meter', 'the organization of beats in music'),
('Beat', 'the basic pulse of music'),
('Tempo', 'the speed of music'),
('Pitch', 'the highness or lowness of a sound'),
('Interval', 'the distance between two pitches'),
('Scale', 'a series of pitches in ascending or descending order'),
('Key', 'the tonal center of a piece'),
('Mode', 'a type of scale'),
('Chord', 'three or more notes played simultaneously'),
('Triad', 'a three-note chord'),
('Seventh chord', 'a four-note chord'),
('Progression', 'a sequence of chords'),
('Cadence', 'a harmonic conclusion'),
('Modulation', 'change from one key to another'),
('Transposition', 'changing the pitch level of a piece'),
('Clef', 'a symbol indicating pitch'),
('Time signature', 'indicates meter and beat grouping'),
('Key signature', 'indicates the key of a piece'),
('Accidental', 'a sharp, flat, or natural sign'),
('Rest', 'a silence of specified duration'),
('Note value', 'the duration of a musical note'),
('Whole note', 'a note lasting four beats in 4/4 time'),
('Half note', 'a note lasting two beats in 4/4 time'),
('Quarter note', 'a note lasting one beat in 4/4 time'),
('Eighth note', 'a note lasting half a beat in 4/4 time'),
('Sixteenth note', 'a note lasting a quarter beat in 4/4 time'),
('Dotted note', 'a note whose duration is increased by half'),
('Triplet', 'three notes played in the time of two'),
('Syncopation', 'emphasis on off-beats'),
('Upbeat', 'the weak beat preceding a strong beat'),
('Downbeat', 'the first beat of a measure'),
('Bar line', 'a vertical line separating measures'),
('Double bar line', 'indicates the end of a section or piece'),
('Repeat sign', 'indicates a section to be repeated'),
('First and second endings', 'different endings for repeated sections'),
('Ostinato', 'a repeated musical pattern'),
('Pedal point', 'a sustained note beneath changing harmonies'),
('Drone', 'a continuous low note'),
('Grace note', 'a decorative note of short duration'),
('Trill', 'rapid alternation between two adjacent notes'),
('Mordent', 'a quick alternation with the note above or below'),
('Turn', 'a four-note ornament around the main note'),
('Appoggiatura', 'a dissonant note that resolves stepwise'),
('Suspension', 'a note held over from one chord to the next'),
('Resolution', 'the movement from dissonance to consonance'),
('Voice leading', 'the smooth movement of individual parts'),
('Part writing', 'the art of combining musical voices');

-- Verify the insert
SELECT COUNT(*) as total_words FROM music_vocabulary;